import type { NextApiRequest, NextApiResponse } from 'next';
import { VertexAI } from '@google-cloud/vertexai';

// Initialize Vertex AI
// Note: We assume the environment is authenticated via 'gcloud auth application-default login'
// or via Cloud Run metadata server.
const projectId = 'arboracle';
const location = 'us-central1';
const vertexAI = new VertexAI({ project: projectId, location: location });

const model = vertexAI.getGenerativeModel({
    model: 'gemini-1.5-flash-001', // Fast, efficient model for synthesis
    generationConfig: {
        maxOutputTokens: 2048,
        temperature: 0.7,
        topP: 0.8,
    },
});

export default async function handler(
    req: NextApiRequest,
    res: NextApiResponse
) {
    if (req.method !== 'POST') {
        return res.status(405).json({ message: 'Method not allowed' });
    }

    const { spores } = req.body;

    if (!spores || !Array.isArray(spores) || spores.length === 0) {
        return res.status(400).json({ message: 'No spores provided for synthesis.' });
    }

    try {
        console.log(`[Arboracle] Synthesizing ${spores.length} spores...`);

        // Construct the prompt
        const sporeContext = spores.map((s: any, i: number) => `SPORE_${i + 1} [Tags: ${s.tags.join(', ')}]: "${s.content}"`).join('\n\n');

        const systemPrompt = `
You are the ARBORACLE, a biosynthetic intelligence engine designed to achieve "Stasis Through Inferred Memory" (STIM).
Your goal is to SYNTHESIZE, not summarize. You must find the hidden "mycelial" connections between these disparate thoughts (Spores).

INPUT: A list of "Spores" (thoughts/notes) from the user's garden.
OUTPUT: A structured "Neocambrian Thesis" in Markdown.

Follow this exact format:
# NEOCAMBRIAN THESIS: [SYNTHESIS-ID]
## SOURCE MATERIAL: ${spores.length} SPORES

---

### [IDENTITY MATRIX]
(One sentence describing the emergent "vibe" or "spirit" of this collection.)

### [THE SYNTHESIS]
(A deep, philosophical, yet actionable paragraph connecting the spores. Use metaphors of ecology, biology, and cybernetics.)

### [CLIMAX INSIGHTS]
1. **[Insight Name]**: [Explanation]
2. **[Insight Name]**: [Explanation]
3. **[Insight Name]**: [Explanation]

### [ACTIONABLE VECTOR]
(One concrete next step to move these ideas from storage to reality.)
`;

        const result = await model.generateContent({
            contents: [{ role: 'user', parts: [{ text: `SYSTEM_INSTRUCTION: ${systemPrompt}\n\nDATA_STREAM:\n${sporeContext}` }] }],
        });

        const responseResponse = await result.response;
        const text = responseResponse.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!text) {
            throw new Error('No content generated by Gemini.');
        }

        res.status(200).json({ thesis: text });
    } catch (error: any) {
        console.error('[Arboracle] Synthesis Error:', error);
        res.status(500).json({
            message: 'Failed to synthesize thesis.',
            error: error.message,
            detail: 'Ensure GCP credentials are set and Vertex AI API is enabled.'
        });
    }
}
