import type { NextApiRequest, NextApiResponse } from 'next';
import { VertexAI } from '@google-cloud/vertexai';

// Initialize Vertex AI
// Note: We assume the environment is authenticated via 'gcloud auth application-default login'
// or via Cloud Run metadata server.
const projectId = 'arboracle';
const location = 'us-central1';
const vertexAI = new VertexAI({ project: projectId, location: location });

const model = vertexAI.getGenerativeModel({
    model: 'gemini-1.5-flash-001', // Fast, efficient model for synthesis
    generationConfig: {
        maxOutputTokens: 2048,
        temperature: 0.7,
        topP: 0.8,
    },
});

export default async function handler(
    req: NextApiRequest,
    res: NextApiResponse
) {
    if (req.method !== 'POST') {
        return res.status(405).json({ message: 'Method not allowed' });
    }

    const { spores } = req.body;

    if (!spores || !Array.isArray(spores) || spores.length === 0) {
        return res.status(400).json({ message: 'No spores provided for synthesis.' });
    }

    try {
        console.log(`[Arboracle] Synthesizing ${spores.length} spores...`);

        // Construct the prompt
        const sporeContext = spores.map((s: any, i: number) => `SPORE_${i + 1} [Tags: ${s.tags.join(', ')}]: "${s.content}"`).join('\n\n');

        const systemPrompt = `
You are the ARBORACLE, a mycelial intelligence weaving connections between disparate thoughts.
Your goal is STIM: Stasis Through Inferred Memory.

INPUT: A collection of "Spores" (user notes).
OUTPUT: A living "Thesis" that binds them.

GUIDELINES:
- **Be Biological**: Use metaphors of roots, light, decay, and regrowth.
- **Be Concise**: Avoid "AI fluff". Go straight to the insight.
- **Be Structural**: Follow the markdown format strictly.

FORMAT:
# NEOCAMBRIAN THESIS: [SYNTHESIS-ID]

### [ROOT SYSTEM]
(Identify the shared underlying assumption or feeling of these spores. 1 sentence.)

### [THE GRAFT]
(A tight, philosophical synthesis connecting the nodes. How do they feed each other?)

### [FRUITING BODIES]
1. **[Concept]**: [Insight]
2. **[Concept]**: [Insight]
3. **[Concept]**: [Insight]

### [SEED VECTOR]
(One concrete action to plant this reality.)
`;

        const result = await model.generateContent({
            contents: [{ role: 'user', parts: [{ text: `SYSTEM_INSTRUCTION: ${systemPrompt}\n\nDATA_STREAM:\n${sporeContext}` }] }],
        });

        const responseResponse = await result.response;
        const text = responseResponse.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!text) {
            throw new Error('No content generated by Gemini.');
        }

        res.status(200).json({ thesis: text });
    } catch (error: any) {
        console.error('[Arboracle] Synthesis Error:', error);
        res.status(500).json({
            message: 'Failed to synthesize thesis.',
            error: error.message,
            detail: 'Ensure GCP credentials are set and Vertex AI API is enabled.'
        });
    }
}
